apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nly0u8w0c-dotnet-basic 
  janus-idp.io/tekton: nly0u8w0c-dotnet-basic
  backstage.io/kubernetes-id: nly0u8w0c-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nly0u8w0c-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml